project:
  name: mlops-churn-prediction
  domain: prediction
  schema_version: v1

model:
  type: sklearn_gb
  params:
    n_estimators: 200
    max_depth: 3
    learning_rate: 0.05


data:
  target_column: Churn
  known_targets: 
    - Churn
  time_column: null
  id_columns:
    - customerID
  primary_keys:
    - []

  feature_sources:
    train:
      path: Telco-Customer-Churn.csv

training:
  validation_strategy: holdout
  test_size: 0.2
  target_transformation: none

metrics:
  primary: f1_score
  secondary:
    - roc_auc
    - accuracy
  evaluate_on_original_scale: true

features:
  features:
  # Define which steps from src/data/features/core.py should run
  enabled_steps:
    - cast_numeric_types
    - encode_categoricals
    - drop_configured

  # These columns need to be cast from String to Float (Notebook logic)
  cast_to_numeric:
    - TotalCharges

  # Categorical features for One-Hot-Encoding
  categorical_columns:
    - gender
    - SeniorCitizen
    - Partner
    - Dependents
    - PhoneService
    - MultipleLines
    - InternetService
    - OnlineSecurity
    - OnlineBackup
    - DeviceProtection
    - TechSupport
    - StreamingTV
    - StreamingMovies
    - Contract
    - PaperlessBilling
    - PaymentMethod

  # Columns that add no value to the model
  drop_columns:
    - customerID